/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSkillsRouteImport } from './routes/_app.skills'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppMediaRouteImport } from './routes/_app.media'
import { Route as AppHighlightsRouteImport } from './routes/_app.highlights'
import { Route as AppExperienceRouteImport } from './routes/_app.experience'
import { Route as AppEducationRouteImport } from './routes/_app.education'
import { Route as AppContactRouteImport } from './routes/_app.contact'
import { Route as AppCertificationsRouteImport } from './routes/_app.certifications'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppActivityRouteImport } from './routes/_app.activity'
import { Route as AppProjectsSlugRouteImport } from './routes/_app.projects.$slug'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMediaRoute = AppMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AppRoute,
} as any)
const AppHighlightsRoute = AppHighlightsRouteImport.update({
  id: '/highlights',
  path: '/highlights',
  getParentRoute: () => AppRoute,
} as any)
const AppExperienceRoute = AppExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => AppRoute,
} as any)
const AppEducationRoute = AppEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => AppRoute,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRoute,
} as any)
const AppCertificationsRoute = AppCertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsSlugRoute = AppProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/activity': typeof AppActivityRoute
  '/analytics': typeof AppAnalyticsRoute
  '/certifications': typeof AppCertificationsRoute
  '/contact': typeof AppContactRoute
  '/education': typeof AppEducationRoute
  '/experience': typeof AppExperienceRoute
  '/highlights': typeof AppHighlightsRoute
  '/media': typeof AppMediaRoute
  '/profile': typeof AppProfileRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/skills': typeof AppSkillsRoute
  '/projects/$slug': typeof AppProjectsSlugRoute
}
export interface FileRoutesByTo {
  '/activity': typeof AppActivityRoute
  '/analytics': typeof AppAnalyticsRoute
  '/certifications': typeof AppCertificationsRoute
  '/contact': typeof AppContactRoute
  '/education': typeof AppEducationRoute
  '/experience': typeof AppExperienceRoute
  '/highlights': typeof AppHighlightsRoute
  '/media': typeof AppMediaRoute
  '/profile': typeof AppProfileRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/skills': typeof AppSkillsRoute
  '/': typeof AppIndexRoute
  '/projects/$slug': typeof AppProjectsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/activity': typeof AppActivityRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/certifications': typeof AppCertificationsRoute
  '/_app/contact': typeof AppContactRoute
  '/_app/education': typeof AppEducationRoute
  '/_app/experience': typeof AppExperienceRoute
  '/_app/highlights': typeof AppHighlightsRoute
  '/_app/media': typeof AppMediaRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/skills': typeof AppSkillsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/projects/$slug': typeof AppProjectsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/analytics'
    | '/certifications'
    | '/contact'
    | '/education'
    | '/experience'
    | '/highlights'
    | '/media'
    | '/profile'
    | '/projects'
    | '/skills'
    | '/projects/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/activity'
    | '/analytics'
    | '/certifications'
    | '/contact'
    | '/education'
    | '/experience'
    | '/highlights'
    | '/media'
    | '/profile'
    | '/projects'
    | '/skills'
    | '/'
    | '/projects/$slug'
  id:
    | '__root__'
    | '/_app'
    | '/_app/activity'
    | '/_app/analytics'
    | '/_app/certifications'
    | '/_app/contact'
    | '/_app/education'
    | '/_app/experience'
    | '/_app/highlights'
    | '/_app/media'
    | '/_app/profile'
    | '/_app/projects'
    | '/_app/skills'
    | '/_app/'
    | '/_app/projects/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/skills': {
      id: '/_app/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/media': {
      id: '/_app/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AppMediaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/highlights': {
      id: '/_app/highlights'
      path: '/highlights'
      fullPath: '/highlights'
      preLoaderRoute: typeof AppHighlightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/experience': {
      id: '/_app/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof AppExperienceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/education': {
      id: '/_app/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof AppEducationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contact': {
      id: '/_app/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/certifications': {
      id: '/_app/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof AppCertificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$slug': {
      id: '/_app/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof AppProjectsSlugRouteImport
      parentRoute: typeof AppProjectsRoute
    }
  }
}

interface AppProjectsRouteChildren {
  AppProjectsSlugRoute: typeof AppProjectsSlugRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsSlugRoute: AppProjectsSlugRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCertificationsRoute: typeof AppCertificationsRoute
  AppContactRoute: typeof AppContactRoute
  AppEducationRoute: typeof AppEducationRoute
  AppExperienceRoute: typeof AppExperienceRoute
  AppHighlightsRoute: typeof AppHighlightsRoute
  AppMediaRoute: typeof AppMediaRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppSkillsRoute: typeof AppSkillsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCertificationsRoute: AppCertificationsRoute,
  AppContactRoute: AppContactRoute,
  AppEducationRoute: AppEducationRoute,
  AppExperienceRoute: AppExperienceRoute,
  AppHighlightsRoute: AppHighlightsRoute,
  AppMediaRoute: AppMediaRoute,
  AppProfileRoute: AppProfileRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppSkillsRoute: AppSkillsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
